export enum Step {
    USER_IDENTIFICATION = "USER_IDENTIFICATION",
    AUTHORIZATION_LINK = "AUTHORIZATION_LINK",
    LOAN_RELEASED = "LOAN_RELEASED",
    USER_ADDRESS = "USER_ADDRESS",
    CHANGE_LOAD = "CHANGE_LOAD",
    USER_BANK = "USER_BANK",
    CHANGE_LOAN = "CHANGE_LOAN",
    AUTHORIZATION_LOAN_LINK = "AUTHORIZATION_LOAN_LINK"
}